create database customer_behavior
use customer_behavior
CREATE TABLE customer (
    customer_id INT PRIMARY KEY,
    age INT,
    gender NVARCHAR(20),
    item_purchased NVARCHAR(100),
    category NVARCHAR(50),
    purchase_amount INT,
    location NVARCHAR(100),
    size CHAR(1),
    color NVARCHAR(30),
    season NVARCHAR(20),
    review_rating DECIMAL(2,1),
    subscription_status NVARCHAR(20),
    shipping_type NVARCHAR(30),
    discount_applied NVARCHAR(10),
    previous_purchases INT,
    payment_method NVARCHAR(30),
    frequency_of_purchases NVARCHAR(50),
    age_group NVARCHAR(20),
    purchase_frequency_days INT
);

select * from customer

--Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as revenue from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount from customer
where discount_applied = 'Yes'and purchase_amount >= (select avg(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, avg(review_rating) as 'average_rating' from customer
group by item_purchased
order by average_rating desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select avg(purchase_amount) as 'Avg_Purchase_Amount', shipping_type from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select  subscription_status, count(customer_id) as Total_Customers, avg(purchase_amount) as Average_Spend, sum(purchase_amount) as Total_Revenue from customer
group by subscription_status
order by total_revenue, Average_Spend

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5

--Q7. Segment customers into 'New', 'Returning', and 'Loyal' based on their total number of previous purchases, and show the count of each segment.
with customer_type as(
select customer_id, previous_purchases,
case
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customer)

select customer_segment, count(*) as "number of customers"
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_order,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_order
from item_counts
where item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers from customer
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as Revenue_Contribution from customer
group by age_group
order by revenue_contribution desc;